### ISSUE TITLE
Contract(create sale invoice error)

### ISSUE THREAD

**Issue by BreytaUrban** [morghim/contract-payment#1]
Hi i am currently facing an issue with the contract payment in ERP next. Whenever i try to click the create sales invoice button under the actions button on the top right, i get the following error code in the attachment (see attachment).what could be wrong

![contract error](https://user-images.githubusercontent.com/92117993/173019766-8a20f946-d582-4f24-a6c9-d587fe295737.PNG)

**Comment by morghim** [comment]
Thank you for using the app 

did you add an account on contract type ?

Please show me your logs

**Comment by morghim** [comment]
need to setup account for item follow docs
